### PR TITLE
Fix hadoop native libraries

### PR DESCRIPTION
**Pull request by codingtony**
See issue #8

### CODE REVIEW

**Comment by davidonlaptop** [comment]
LGTM.

Can you create another ticket for the missing native bzip2 ?

**Comment by mikefaille** [comment]
@codingtony  Did you test Snappy et bzip using this patch ?

**Comment by codingtony** [comment]
For bzip2 I think that the binary distribution haven't been compiled with libbzip2.

If I rebuild hadoop from source I can make libbzip2 available natively. However it takes a while to build and a lot of packages are needed for the compilation.

I think it might be related to https://issues.apache.org/jira/browse/HADOOP-10409

Compiled from source and installed : 

```
strings /usr/local/hadoop/lib/native/libhadoop.so | grep initIDs | grep bz
Java_org_apache_hadoop_io_compress_bzip2_Bzip2Compressor_initIDs
Java_org_apache_hadoop_io_compress_bzip2_Bzip2Decompressor_initIDs
Java_org_apache_hadoop_io_compress_bzip2_Bzip2Compressor_initIDs
Java_org_apache_hadoop_io_compress_bzip2_Bzip2Decompressor_initIDs
Java_org_apache_hadoop_io_compress_bzip2_Bzip2Compressor_initIDs
Java_org_apache_hadoop_io_compress_bzip2_Bzip2Decompressor_initIDs
```

Binary distribution (that was downloaded by the Dockerfile) :

```
strings /usr/local/hadoop/lib/native/libhadoop.so | grep initIDs | grep bz
#returns nothing
```

I'll test snappy, but I'm not sure yet what's the fastest way to do it.

**Comment by codingtony** [comment]
For the records HOW TO BUILD (will be moved to the wiki eventually) :

Using gelog/hadoop :

```
apt-get update
wget http://archive.apache.org/dist/hadoop/core/hadoop-2.6.0/hadoop-2.6.0-src.tar.gz
tar xvzf hadoop-2.6.0-src.tar.gz
cd hadoop-2.6.0-src
apt-get install build-essential maven autoconf automake cmake g++ zlib1g-dev liblzma-dev libssl-dev libtool zlib1g-dev pkg-config libssl-dev protobuf-compiler libbz2-dev libsnappy-dev
mvn package -Pdist,native -DskipTests -Dtar
```

The tar ends up here : `hadoop-dist/target/hadoop-2.6.0.tar.gz`

**Comment by davidonlaptop** [comment]
> I think it might be related to https://issues.apache.org/jira/browse/HADOOP-10409

Yeah, it definitely seems related to this. If that is a bug upstream, then we should probably wait for the Hadoop team to fix it.

**Comment by davidonlaptop** [comment]
Notes for correction: this issue was partially resolved. See #29 .

**Pull request merged**
